
#spring:
#  security:
#    oauth2:
#      clientId: ????
#      clientSecret: ????

spring:
  security:
    oauth2:
      client:
        registration:
            google:
                clientId: 841826356567-95s5dgc0hglpj2p015sefimakbdgr28o.apps.googleusercontent.com
                clientSecret: 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
                scope:
                  - email
                  - profile
                redirect-uri: http://localhost:8080/login/oauth2/code/google
                token-uri: https://oauth2.googleapis.com/token
                resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

# https://accounts.google.com/o/oauth2/auth?client_id=CLIENT_ID&redirect_uri=REDIRECT_URI&response_type=code&scope=https://www.googleapis.com/auth/userinfo.emailhttps://www.googleapis.com/auth/userinfo.profile
# https://accounts.google.com/o/oauth2/auth?client_id=841826356567-95s5dgc0hglpj2p015sefimakbdgr28o.apps.googleusercontent.com&redirect_uri=http://localhost:8080/login/oauth2/code/google&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile