spring:
#  profiles:
#    include: oauth
  mvc:
    servlet:
      path: /api/
  h2:
    # 웹으로 확인
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
#    url: jdbc:h2:~/spring-qna-db # embedded Mode : db 데이터 저장 위치 :  ~/spring-qna-db
    url: jdbc:h2:mem:test # In-Memory mode
    username: sa
    password:
# spring - h2 연결
#spring.datasource.url=jdbc:h2:mem:test # In-Memory mode
#spring.datasource.username=sa
#spring.datasource.password=
  sql:
    init:
      mode: always
#spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql

